### ISSUE TITLE
[Suggestion] 请问可否在烹饪界面加一个结果预测显示

### ISSUE THREAD

**Issue by joe-vettek** [TeamMoegMC/Thermopolium#1]
### Suggestion

希望能在烹饪界面加一个结果预测显示，降低新手上手难度。

### Reason

看书的物品比例没太明白，后面才发现是4个物品=1L液体，这样算浓度，之前一直钉子汤莫名其妙的，感觉上手不太方便。

### Exsiting Mods

暂时没有印象。

**Comment by joe-vettek** [comment]
我感觉浓度要求还是很严格的。

**Comment by khjxiaogu** [comment]
首先，配方并不是必须的，只是改变外观而已，即便不按照配方也能做出不错的汤，所以我不认为展示配方是重要的。既然不重要，那就没有知道的必要性。
其次，我们希望带来一种沉浸、真实的体验，只有做出来才能知道是什么汤，就好比做菜一样，不做出来怎么知道口味和外观如何？
