### ISSUE TITLE
[Support] 添加常用食物模组的配方支持

### ISSUE THREAD

**Issue by ColdTearsYY** [TeamMoegMC/Thermopolium#2]
### Mod(s) to support

比如
简单农业https://www.mcmod.cn/class/1874.html
沉浸烹饪https://www.mcmod.cn/class/4299.html
Alex生物https://www.mcmod.cn/class/3318.html

### What to support

食材配方支持

**Comment by khjxiaogu** [comment]
Support contents must be specify, this issue is consider invalid and such support would not be added
