### ISSUE TITLE
[Bug] 无法在开发环境加载

### ISSUE THREAD

**Issue by joe-vettek** [TeamMoegMC/Thermopolium#4]
### Error Behaviour

![Uploading image.png…]()

### Expected Behaviour

可以在开发环境加载

### Reproduce

    implementation fg.deobf("curse.maven:patchouli-306770:3459118")
    implementation fg.deobf("curse.maven:thermopolium-594107:3694288")

### Crash Report

https://pastebin.com/UT6j1uaN

### Mod version

0.2

**Comment by khjxiaogu** [comment]
We are using MCP mappings, which does NOT always compatible with official mappings.
If you are really a dev, you shouldn't ask about this.
Use MCP mappings OR SOLVE ON YOUR OWN.

**Comment by joe-vettek** [comment]
1.16.5的情况复杂，我忘记了，刚才看了看你们使用的是36.2.4，确实不好弄。我使用官表是为了方便移植到1.18，多谢告知。
